Fix arch specific download

diff --git a/5.8/ubuntu/20.04/Dockerfile b/5.8/ubuntu/20.04/Dockerfile
--- a/5.8/ubuntu/20.04/Dockerfile
+++ b/5.8/ubuntu/20.04/Dockerfile
@@ -25,11 +25,22 @@ RUN export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true && ap
 
 
 ARG SWIFT_TAG=swift-wasm-5.8.0-RELEASE
-ENV SWIFT_PLATFORM_SUFFIX=ubuntu20.04_x86_64.tar.gz
+ENV SWIFT_PLATFORM=ubuntu20.04
 ENV SWIFT_TAG=$SWIFT_TAG
 
 RUN set -e; \
-    SWIFT_BIN_URL="https://github.com/swiftwasm/swift/releases/download/$SWIFT_TAG/$SWIFT_TAG-$SWIFT_PLATFORM_SUFFIX" \
+    ARCH_NAME="$(dpkg --print-architecture)"; \
+    url=; \
+    case "${ARCH_NAME##*-}" in \
+        'amd64') \
+            OS_ARCH_SUFFIX='x86_64'; \
+            ;; \
+        'arm64') \
+            OS_ARCH_SUFFIX='aarch64'; \
+            ;; \
+        *) echo >&2 "error: unsupported architecture: '$ARCH_NAME'"; exit 1 ;; \
+    esac; \
+    SWIFT_BIN_URL="https://github.com/swiftwasm/swift/releases/download/$SWIFT_TAG/$SWIFT_TAG-${SWIFT_PLATFORM}_${OS_ARCH_SUFFIX}.tar.gz" \
     && export DEBIAN_FRONTEND=noninteractive \
     && apt-get -q update && apt-get -q install -y curl && rm -rf /var/lib/apt/lists/* \
     && curl -fsSL "$SWIFT_BIN_URL" -o swift.tar.gz \
